import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_DIVIDER
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    /** Example purpose only, please remove */
    {
        key: 'uploadData',
        path: '/upload-data',
        title: 'Upload Data',
        translateKey: 'nav.uploadData',
        icon: 'uploadCsv',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'showData',
        path: '/show-data',
        title: 'My Files',
        translateKey: 'nav.showData',
        icon: 'showCsv',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'talkToData',
        path: '/talk-to-data',
        title: 'Talk to Data',
        translateKey: 'nav.talkToData',
        icon: 'talkToData',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'ruleCenter',
        path: '/rule-center',
        title: 'Rule Center',
        translateKey: 'nav.ruleCenter',
        icon: 'ruleCenter',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'generateSyntheticData',
        path: '/generate-synthetic-data',
        title: 'Generate Synthetic Data',
        translateKey: 'nav.generateSyntheticData',
        icon: 'generateSyntheticData',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'dataProcessing',
        path: '/data-processing',
        title: 'Data Processing',
        translateKey: 'nav.dataProcessing',
        icon: 'dataProcessing',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'preprocessing',
                path: '/preprocessing',
                title: 'Data Preprocessing',
                translateKey: 'nav.preprocessing',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'mlModels',
                path: '/ml-models',
                title: 'ML Models',
                translateKey: 'nav.mlModels',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'postProcessing',
                path: '/post-processing',
                title: 'Post Processing',
                translateKey: 'nav.postProcessing',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'userLists',
        path: '/user-lists',
        title: 'User Lists',
        translateKey: 'nav.userLists',
        icon: 'userLists',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'divider1',
        path: '',
        title: '',
        translateKey: '',
        type: NAV_ITEM_TYPE_DIVIDER,
        authority: [],
        subMenu: [],
    },
    {
        key: 'pricing',
        path: '/pricing',
        title: 'Pricing',
        translateKey: 'nav.pricing',
        icon: 'pricing',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'billing',
        path: '/billing',
        title: 'Billing & Usage',
        translateKey: 'nav.billing',
        icon: 'billing',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'divider2',
        path: '',
        title: '',
        translateKey: '',
        type: NAV_ITEM_TYPE_DIVIDER,
        authority: [],
        subMenu: [],
    },
    {
        key: 'feedback',
        path: '/feedback',
        title: 'Feedback',
        translateKey: 'nav.feedback',
        icon: 'feedback',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    }
]

export default navigationConfig
